### ISSUE TITLE
Need to fix the assertion in the test for asset_class_advisor

### ISSUE THREAD

**Issue by amkolhar** [highwire-ai/open-robo-advisor#22]
https://github.com/highwire-ai/open-robo-advisor/blob/b24cbed73856937bd2c11df10e1d565733e191b2/tests/openroboadvisor_tests/advisor/test_asset_class_advisor.py

In line 56, the assertion failure message is set wrong ( or just copied from the other test). The required message in the test is supposed to be `Expected 2.0933 SPY shares.`

The test when fails will lead to the wrong failure message.

**Comment by criccomini** [comment]
Ah, good catch!
